apiVersion: v1
kind: Service
metadata:
  name: my-python-service
  labels:
    app: my-app
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - port: 80              # Port on the Service
      targetPort: 8000     # Port on the Pod (container port)
      nodePort: 30007        # Port on the Node (range: 30000-32767)

